config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  get "sign_up", to: "sign_ups#new"
  resource :sign_up, only: [:create] do
    resource :confirmation, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/aura.rb
class Aura < ApplicationRecord
  belongs_to :user

  encrypts :zip_code, deterministic: true
  encrypts :content

  before_create do
    self.zip_code ||= user.zip_code
    self.temperature_in_fahrenheit ||= user.current_temp_in_fahrenheit
    generate_content
  end

  def generate_content
    self.content = "Good #{part_of_day}, #{user.first_name}! It's gonna be #{description_of_weather} - #{suggestion}"
  end

  def deliver
    client = Twilio::REST::Client.new
    client.messages.create(
      messaging_service_sid: Rails.application.credentials.dig(:twilio, :messaging_service_sid),
      to: user.phone_number,
      body: content
    )

    update!(delivered_at: Time.now)
  end

  private

  def part_of_day
    hour = Time.use_zone(Ziptz.instance.time_zone_name(user.zip_code)) { Time.current.hour }
    if hour < 12
      "morning"
    elsif hour < 18
      "afternoon"
    else
      "evening"
    end
  end

  def description_of_weather
    "around #{temperature_in_fahrenheit} degrees today"
  end

  def suggestion
    "#{suggestion_prefix} #{apparel_suggestion}"
  end

  def suggestion_prefix
    [
      "you should definitely",
      "it might be a good day to",
      "a human like yourself might even",
      "you'd be crazy not to",
      "it's a no-brainer to",
      "it's so good, even your grandma would",
      "don't be a chicken, go ahead and",
      "if you don't, the universe might implode",
      "it's like finding a dollar on the sidewalk – you have to",
      "the weather gods demand that you",
      "do it for the vine! Or, you know, just because you should",
      "if you're feeling brave, you could",
      "this is your chance to be a weather warrior and",
      "you won't regret it if you"
    ].sample
  end

  def apparel_suggestion
    case temperature_in_fahrenheit
    when -Float::INFINITY...0
      "bundle up in your warmest coat, hat, and gloves to stay cozy today - don't get frostbite!"
    when 0...10
      "wear a thick sweater, scarf, and beanie will keep you comfortable... hopefully..."
    when 10...20
      "wear a warm jacket, jeans, and boots to keep you toasty."
    when 20...30
      "layer up with a sweater, jacket, and cozy socks."
    when 30...40
      "take a brisk morning walk with a light jacket, leggings, and sneakers."
    when 40...50
      "grab a light jacket and a pair of jeans for a comfortable day."
    when 50...60
      "enjoy the nice temperature with a light sweater and shorts."
    when 60...70
      "perfect weather for a t-shirt and shorts. Get outside and soak up the sunshine!"
    when 70...90
      "wear a hat, sunglasses, and light, breathable clothing."
    else
      "stay cool and hydrated B-)"
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  encrypts :first_name
  encrypts :phone_number, :zip_code, deterministic: true

  validates :first_name, presence: true, length: {maximum: 22}

  before_validation -> { self.phone_number = Phonelib.parse(phone_number).e164 }, if: -> { Phonelib.valid?(phone_number) }
  validates :phone_number, uniqueness: true, phone: {possible: true, countries: [:us]}

  validates :zip_code, zipcode: {country_code: :us}
  validate :zip_code_exists, if: -> { errors.none? }

  has_many :auras

  def current_temp_in_fahrenheit
    connection = Faraday.new("https://api.weatherapi.com") { |connection| connection.response :json }
    response = connection.get("/v1/forecast.json?key=#{Rails.application.credentials.weatherapi_key!}&q=#{zip_code}&days=1&aqi=no&alerts=no")

    if (temp = response.body.dig("current", "temp_f"))
      temp.to_i
    end
  end

  private

  def zip_code_exists
    if current_temp_in_fahrenheit.nil? && with(zip_code: "02462") { current_temp_in_fahrenheit.present? }
      errors.add(:zip_code, "does not exist")
    end
  end
end

app/models/user/status.rb
module User::Status
  extend ActiveSupport::Concern

  included do
    enum status: {pending: 0, active: 1, inactive: 2}
  end
end

app/models/user/verifiable.rb
module User::Verifiable
  extend ActiveSupport::Concern

  included do
    after_create_commit -> { request_verification }

    scope :verified, -> { not_pending }
  end

  def verified?
    status != :pending
  end

  def request_verification
    update!(status: :pending)
  end

  def verify
    update!(status: :active) unless verified?
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  def create
    user = User.new(user_params)

    if user.save
      render json: user, status: :created
    else
      head :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :phone_number, :zip_code)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sign_ups/confirmations_controller.rb
class SignUps::ConfirmationsController < ApplicationController
  def show
  end
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to sign_up_confirmation_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :phone_number, :zip_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<div class="flex min-h-full flex-col justify-center p-10">
  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Aurora Alerts</h2>
  </div>

  <div class="mt-5 sm:mx-auto sm:w-full sm:max-w-sm">
    <form class="space-y-5" action="#">
      <div>
        <label for="email" class="block text-sm font-medium leading-6 text-gray-900">Email address</label>
        <div class="mt-2">
          <input id="email" name="email" type="email" autocomplete="email" required class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
        <div class="mt-2">
          <input id="password" name="password" type="password" autocomplete="current-password" required class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
        </div>
      </div>

      <div>
        <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Sign in</button>
      </div>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aurora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sign_ups/new.html.erb
<%= turbo_frame_tag :sign_up do %>
  <%= form_with url: sign_up_path, model: @user do |form| %>
    <% if @user.errors.any? %>
      <div class="red">
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
    </div>

    <div class="mb-4">
    <%= form.label :phone_number %>
    <%= form.phone_field :phone_number %>
    </div>

    <div class="mb-4">
    <%= form.label :zip_code, "ZIP code" %>
    <%= form.text_field :zip_code %>
    </div>

    <div>
    <%= form.button "Sign Up" %>
    </div>
  <% end %>
<% end %>